package me.dnfneca.plugin;

import me.dnfneca.plugin.Commands.*;
import me.dnfneca.plugin.listeners.*;
import me.dnfneca.plugin.utilities.GUI.Waystone;
import me.dnfneca.plugin.utilities.managers.CustomMobs.*;
import me.dnfneca.plugin.utilities.managers.Item.Item;
import me.dnfneca.plugin.utilities.managers.Item.Reforge;
import me.dnfneca.plugin.utilities.managers.Item.SetOpenedInventoryItemsLore;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.plugin.java.JavaPlugin;
import org.checkerframework.checker.nullness.qual.NonNull;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import static me.dnfneca.plugin.listeners.PlayerJoin.CustomMobs;

public final class Plugin extends JavaPlugin {
	public static List<Item> CustomItems = new ArrayList<>();
	public static List<Reforge> CustomReforges = new ArrayList<>();


	@Override
	public void onEnable() {

		final File f = new File("./plugins/MMORPGData");

		if (f.mkdir()) {
			System.out.println("Directory has been created successfully");
		} else {
			System.out.println("Directory cannot be created");
		}


		// Plugin startup logic


		final Plugin instance = this;

		getCommand("summonmob").setExecutor(new @NonNull summonmob());
		getCommand("summonmob").setTabCompleter(new summonTabComplete());
		getCommand("giveitem").setExecutor(new @NonNull giveitem());
		getCommand("giveitem").setTabCompleter(new itemTabComplete());
		getCommand("classreset").setExecutor(new @NonNull classreset());
		getCommand("GOD").setExecutor(new God());
		getCommand("GUI").setExecutor(new GUI());
		getCommand("spawnWaystone").setExecutor(new spawnWaystone());
		getCommand("test").setExecutor(new test());
		getCommand("setLevel").setExecutor(new setLevel());


		//  MOBS

        this.getServer().getPluginManager().registerEvents(new BasicSpider(this), this);
        this.getServer().getPluginManager().registerEvents(new BasicWolf(this), this);
        this.getServer().getPluginManager().registerEvents(new Dummy(this), this);
        this.getServer().getPluginManager().registerEvents(new Ghoul(this), this);


		// EVENTS


        this.getServer().getPluginManager().registerEvents(new InventoryListener(), this);
        this.getServer().getPluginManager().registerEvents(new AttackListener(), this);
        this.getServer().getPluginManager().registerEvents(new FishingListener(), this);
        this.getServer().getPluginManager().registerEvents(new PlayerHealthListener(), this);
        this.getServer().getPluginManager().registerEvents(new PlayerJoin(this), this);
        this.getServer().getPluginManager().registerEvents(new PlayerLeave(), this);
        this.getServer().getPluginManager().registerEvents(new RightClickListener(), this);
        this.getServer().getPluginManager().registerEvents(new CraftingTableListener(), this);
        this.getServer().getPluginManager().registerEvents(new DropItemListener(), this);
        this.getServer().getPluginManager().registerEvents(new ForgeMenuListener(), this);
        this.getServer().getPluginManager().registerEvents(new Waystone(), this);
        this.getServer().getPluginManager().registerEvents(new SetOpenedInventoryItemsLore(), this);

//        getServer().getPluginManager().registerEvents(new (this), this);

		// Classes


		// ITEMS

        Plugin.CustomItems.add(new Item("ARMOR",
				100,
				0,
				50,
				0,
				0,
				0,
				0,
				0,
				0,
				"none",
				"Iron Sex",
				"Rare",
				Material.IRON_CHESTPLATE,
				"ARMOR",
				0,
				"Armor",
				0,
				0));

        Plugin.CustomItems.add(new Item("Sticky",
				100,
				0,
				50,
				0,
				0,
				0,
				0,
				0,
				0,
				"test",
				"Iron Sex",
				"Rare",
				Material.STICK,
				"STICKY",
				0,
				"Weapon",
				0,
				0));

        Plugin.CustomItems.add(new Item("Ghost Reaver",
				0,
				345,
				0,
				220,
				0,
				0,
				730,
				90,
				0,
				"Fireball",
				"none",
				"Rare",
				Material.DIAMOND_HOE,
				"GHOST_REAVER",
				1,
				"Weapon",
				0,
				0));


        Plugin.CustomItems.add(new Item("The Oculus",
				0,
				125,
				0,
				30,
				0,
				0,
				100,
				20,
				0,
				"none",
				"none",
				"Rare",
				Material.IRON_SWORD,
				"THE_OCOLUS",
				0,
				"Weapon",
				10,
				0));
        Plugin.CustomItems.add(new Item("Destiny's Song",
				0,
				+75,
				0,
				+50,
				0,
				0,
				+50,
				+70,
				0,
				"none",
				"none",
				"Rare",
				Material.BOW,
				"DESTINYS_SONG",
				0,
				"Weapon",
				12,
				0));
        Plugin.CustomItems.add(new Item("Hunting Bow",
				0,
				+75,
				0,
				+100,
				0,
				0,
				+50,
				+10,
				0,
				"none",
				"none",
				"Uncommon",
				Material.BOW,
				"HUNTING_BOW",
				0,
				"Weapon",
				0,
				0));
        Plugin.CustomItems.add(new Item("Death's Kiss",
				0,
				+140,
				0,
				+85,
				0,
				0,
				+230,
				+45,
				0,
				"none",
				"none",
				"Mythic",
				Material.BOW,
				"DEATHS_KISS",
				0,
				"Weapon",
				70,
				0));

        Plugin.CustomItems.add(new Item("Longblade of Decay",
				0,
				+75,
				0,
				+50,
				0,
				0,
				+45,
				+15,
				0,
				"none",
				"none",
				"Uncommon",
				Material.STONE_SWORD,
				"LONGBLADE_OF_DECAY",
				0,
				"Weapon",
				0,
				0));
        Plugin.CustomItems.add(new Item("Void Etcher",
				0,
				+150,
				0,
				+120,
				0,
				0,
				+75,
				+55,
				0,
				"none",
				"none",
				"Legendary",
				Material.DIAMOND_SWORD,
				"VOID_ETCHER",
				0,
				"Weapon",
				50,
				0));
        Plugin.CustomItems.add(new Item("Light's Bane",
				0,
				+110,
				0,
				+100,
				0,
				0,
				+45,
				+35,
				0,
				"none",
				"none",
				"Rare",
				Material.IRON_SWORD,
				"LIGHTS_BANE",
				0,
				"Weapon",
				15,
				0));
        Plugin.CustomItems.add(new Item("Hermit's Amulet",
				+25,
				-35,
				+20,
				-5,
				-50,
				+50,
				0,
				+100,
				-10,
				"none",
				"none",
				"Exotic",
				Material.LEATHER_CHESTPLATE,
				"PJ_HERM_AMU",
				0,
				"Armor",
				0,
				0));
        Plugin.CustomItems.add(new Item("Nether's Bane",
				0,
				+160,
				0,
				+120,
				0,
				0,
				+75,
				+45,
				0,
				"none",
				"none",
				"Mythic",
				Material.NETHERITE_SWORD,
				"NETHERS_BANE",
				0,
				"Weapon",
				30,
				0));

        Plugin.CustomItems.add(new Item("Willbreaker",
				0,
				+80,
				0,
				+95,
				0,
				0,
				+20,
				+25,
				0,
				"none",
				"none",
				"Rare",
				Material.IRON_SWORD,
				"WILLBREAKER",
				0,
				"Weapon",
				12,
				0));

        Plugin.CustomItems.add(new Item("Instigator",
				-50,
				+100,
				-20,
				+20,
				+5,
				-5,
				+10,
				+10,
				-10,
				"none",
				"none",
				"Epic",
				Material.WOODEN_SWORD,
				"PJ_INSTI",
				0,
				"Weapon",
				35,
				0));

        Plugin.CustomItems.add(new Item("Hermit's Helmet",
				0,
				0,
				0,
				0,
				0,
				10000000,
				0,
				0,
				-100,
				"none",
				"none",
				"Exotic",
				Material.LEATHER_HELMET,
				"PJ_HERM_HELM",
				0,
				"Armor",
				0,
				0));

        Plugin.CustomItems.add(new Item("Silver Staff",
				+0,
				+35,
				+0,
				+25,
				+0,
				+20,
				+10,
				+5,
				+0,
				"none",
				"none",
				"Common",
				Material.STICK,
				"SILVER_STAFF",
				0,
				"Weapon",
				0,
				0));
        Plugin.CustomItems.add(new Item("Short Bow",
				+0,
				+25,
				+0,
				+20,
				+20,
				+0,
				+10,
				+25,
				+0,
				"Rapid Fire",
				"none",
				"Common",
				Material.BOW,
				"SHORT_BOW",
				0,
				"Weapon",
				0,
				0));
        Plugin.CustomItems.add(new Item("Copper Bow",
				+0,
				+30,
				+0,
				+25,
				+10,
				+0,
				+15,
				+20,
				+0,
				"none",
				"none",
				"Common",
				Material.BOW,
				"COPPER_BOW",
				0,
				"Weapon",
				0,
				0));
        Plugin.CustomItems.add(new Item("Silver Bow",
				+0,
				+40,
				+0,
				+25,
				+5,
				+0,
				+15,
				+10,
				+25,
				"none",
				"none",
				"Common",
				Material.BOW,
				"SILVER_BOW",
				0,
				"Weapon",
				0,
				0));
        Plugin.CustomItems.add(new Item("Shadowsong",
				+0,
				+130,
				+0,
				+140,
				+0,
				+0,
				+70,
				+55,
				+20,
				"none",
				"none",
				"Legendary",
				Material.DIAMOND_SWORD,
				"SHADOWSONG",
				0,
				"Weapon",
				50,
				0));
        Plugin.CustomItems.add(new Item("Quicksilver dagger",
				+0,
				+155,
				+0,
				+115,
				+25,
				+0,
				+0,
				+100,
				+5,
				"none",
				"none",
				"Legendary",
				Material.IRON_SWORD,
				"QUICKSILVER_DAGGER",
				0,
				"Weapon",
				50,
				0));
        Plugin.CustomItems.add(new Item("Dragonclaw",
				+0,
				+90,
				+0,
				+65,
				+0,
				+0,
				+25,
				+20,
				+0,
				"none",
				"none",
				"Uncommon",
				Material.STONE_SWORD,
				"DRAGONCLAW",
				0,
				"Weapon",
				0,
				0));
        Plugin.CustomItems.add(new Item("Sacrificial dagger",
				+0,
				+115,
				+0,
				+75,
				+0,
				+0,
				+50,
				+55,
				+0,
				"none",
				"none",
				"Rare",
				Material.IRON_SWORD,
				"SACRIFICIAL_DAGGER",
				0,
				"Weapon",
				20,
				0));
        Plugin.CustomItems.add(new Item("Nights Edge",
				+0,
				+215,
				+0,
				+135,
				+0,
				+0,
				+70,
				+50,
				+0,
				"none",
				"none",
				"Legendary",
				Material.DIAMOND_SWORD,
				"NIGHTS_EDGE",
				0,
				"Weapon",
				60,
				0));
        Plugin.CustomItems.add(new Item("Windcaller",
				+0,
				+110,
				+0,
				+0,
				+0,
				+45,
				+25,
				+40,
				+0,
				"none",
				"none",
				"Rare",
				Material.BLAZE_ROD,
				"WINDCALLER",
				0,
				"Weapon",
				35,
				0));

        Plugin.CustomItems.add(new Item("Longsword",
				+0,
				+55,
				+0,
				+10,
				+0,
				+0,
				+40,
				+20,
				+0,
				"reach 5",
				"none",
				"Uncommon",
				Material.IRON_SWORD,
				"LONGSWORD",
				1,
				"Weapon",
				5,
				0));

        Plugin.CustomItems.add(new Item("The Void",
				+0,
				+120,
				+0,
				+70,
				+0,
				+60,
				+55,
				+45,
				+0,
				"reality warp (teleport 10 blocks in the direction your looking -30 mana)",
				"none",
				"Rare",
				Material.DIAMOND_SWORD,
				"THE_VOID",
				0,
				"Weapon",
				20,
				0));
        Plugin.CustomItems.add(new Item("Holy Iron Sword",
				+0,
				+40,
				+0,
				+30,
				+0,
				+0,
				+15,
				+5,
				+0,
				"none",
				"none",
				"Common",
				Material.DIAMOND_SWORD,
				"HOLY_IRON_SWORD",
				0,
				"Weapon",
				2,
				0));
        Plugin.CustomItems.add(new Item("Mithrill blade",
				+0,
				+80,
				+0,
				+65,
				+0,
				+0,
				+30,
				+10,
				+0,
				"none",
				"none",
				"Rare",
				Material.IRON_SWORD,
				"MITHRILL_BLADE",
				0,
				"Weapon",
				24,
				0));
        Plugin.CustomItems.add(new Item("Bloodquench",
				+0,
				+100,
				+0,
				+75,
				+0,
				+0,
				+55,
				+30,
				+0,
				"none",
				"none",
				"Rare",
				Material.WOODEN_SWORD,
				"BLOODQUENCH",
				0,
				"Weapon",
				22,
				0));

        Plugin.CustomItems.add(new Item("Firethorn",
				+0,
				+85,
				+0,
				+60,
				+0,
				+0,
				+20,
				+5,
				+0,
				"Fireball",
				"none",
				"Common",
				Material.GOLDEN_SWORD,
				"FIRETHORN",
				0,
				"Weapon",
				0,
				0));
        Plugin.CustomItems.add(new Item("Winterthorn",
				+0,
				+90,
				+0,
				+55,
				+0,
				+0,
				+10,
				+25,
				+0,
				"Snowball",
				"none",
				"Common",
				Material.GOLDEN_SWORD,
				"WINTERTHORN",
				0,
				"Weapon",
				0,
				0));

        Plugin.CustomItems.add(new Item("Soulkeeper",
				+0,
				+100,
				+0,
				+0,
				+0,
				+35,
				+30,
				+45,
				+0,
				"none",
				"none",
				"Rare",
				Material.BLAZE_ROD,
				"SOULKEEPER",
				0,
				"Weapon",
				32,
				0));
        Plugin.CustomItems.add(new Item("Spiritcaster",
				+0,
				+80,
				+0,
				+0,
				+0,
				+25,
				+20,
				+15,
				+0,
				"none",
				"none",
				"Rare",
				Material.BLAZE_ROD,
				"SPIRITCASTER",
				0,
				"Weapon",
				25,
				0));
        Plugin.CustomItems.add(new Item("Greatstaff",
				+0,
				+75,
				+0,
				+0,
				+0,
				+20,
				+15,
				+10,
				+0,
				"none",
				"none",
				"Uncommon",
				Material.STICK,
				"GREATSTAFF",
				0,
				"Weapon",
				0,
				0));
        Plugin.CustomItems.add(new Item("staff of summoning",
				+0,
				+100,
				+0,
				+0,
				+0,
				+55,
				+25,
				+10,
				+0,
				"none",
				"none",
				"Rare",
				Material.BLAZE_ROD,
				"STAFF_OF_SUMMONING",
				0,
				"Weapon",
				27,
				0));
        Plugin.CustomItems.add(new Item("Greatstaff of decay",
				+0,
				+95,
				+0,
				+0,
				+0,
				+55,
				+30,
				+10,
				+0,
				"none",
				"none",
				"Rare",
				Material.BLAZE_ROD,
				"GREATSTAFF_OF_DECAY",
				0,
				"Weapon",
				25,
				0));
        Plugin.CustomItems.add(new Item("Spiritstaff",
				+0,
				+75,
				+0,
				+0,
				+0,
				+50,
				+20,
				+15,
				+0,
				"none",
				"none",
				"Rare",
				Material.BLAZE_ROD,
				"SPIRITSTAFF",
				0,
				"Weapon",
				22,
				0));
        Plugin.CustomItems.add(new Item("Warden Staff",
				+0,
				+60,
				+0,
				+0,
				+0,
				+35,
				+10,
				+5,
				+0,
				"none",
				"none",
				"Uncommon",
				Material.STICK,
				"WARDEN_STAFF",
				0,
				"Weapon",
				12,
				0));
        Plugin.CustomItems.add(new Item("Nightstaff",
				+0,
				+120,
				+0,
				+0,
				+0,
				+75,
				+45,
				+50,
				+0,
				"none",
				"none",
				"Legendery",
				Material.BLAZE_ROD,
				"NIGHTSTAFF",
				0,
				"Weapon",
				48,
				0));
        Plugin.CustomItems.add(new Item("Silverlight",
				+0,
				+100,
				+0,
				+120,
				+0,
				+70,
				+55,
				+45,
				+0,
				"none",
				"none",
				"Legendery",
				Material.NETHERITE_SWORD,
				"SILVERLIGHT",
				0,
				"Weapon",
				52,
				0));
        Plugin.CustomItems.add(new Item("Lightbane",
				+0,
				+100,
				+0,
				+110,
				+0,
				+65,
				+60,
				+40,
				+0,
				"none",
				"none",
				"Legendery",
				Material.DIAMOND_SWORD,
				"LIGHTBANE",
				0,
				"Weapon",
				42,
				0));
        Plugin.CustomItems.add(new Item("Doomblade",
				+0,
				+120,
				+0,
				+80,
				+0,
				+45,
				+50,
				+35,
				+0,
				"none",
				"none",
				"Rare",
				Material.IRON_SWORD,
				"DOOMBLADE",
				0,
				"Weapon",
				32,
				0));
        Plugin.CustomItems.add(new Item("Cataclysm",
				+0,
				+130,
				+0,
				+120,
				+0,
				+260,
				+75,
				+50,
				+0,
				"none",
				"none",
				"Legendary",
				Material.DIAMOND_SWORD,
				"CATACLYSM",
				0,
				"Weapon",
				64,
				0));
        Plugin.CustomItems.add(new Item("Dawn",
				+0,
				+70,
				+0,
				+55,
				+0,
				+30,
				+10,
				+5,
				+0,
				"none",
				"none",
				"Common",
				Material.GOLDEN_SWORD,
				"DAWN",
				0,
				"Weapon",
				0,
				0));
        Plugin.CustomItems.add(new Item("Unholy Great Sword",
				+0,
				+106,
				+0,
				+95,
				+0,
				+30,
				+35,
				+30,
				+0,
				"none",
				"none",
				"Rare",
				Material.GOLDEN_SWORD,
				"UNHOLY_GREAT_SWORD",
				0,
				"Weapon",
				35,
				-3));


        Plugin.CustomItems.add(new Item("Black great Sword",
				+0,
				+125,
				+0,
				+120,
				+0,
				+0,
				+70,
				+25,
				+0,
				"none",
				"none",
				"Rare",
				Material.IRON_SWORD,
				"BLACK_GREAT_SWORD",
				0,
				"Weapon",
				42,
				-3.9));


        Plugin.CustomReforges.add(new Reforge("Strength Artifact",
				10,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				"Rare",
				new ItemStack(Material.ARROW).getItemMeta(),
				"Strong",
				0,
				"Any",
				0));

		Plugin.CustomReforges.add(new Reforge("Arnid's Stoat",
				0,
				0,
				0,
				0,
				20,
				20,
				0,
				0,
				2,
				"Legendary",
				new ItemStack(Material.ARROW).getItemMeta(),
				"Enthusiastic",
				0,
				"Any",
				0));
		Plugin.CustomReforges.add(new Reforge("Raven's Raven",
				20,
				0,
				10,
				0,
				0,
				5,
				0,
				0,
				30,
				"Legendary",
				new ItemStack(Material.ARROW).getItemMeta(),
				"Ravenous",
				0,
				"Any",
				0));
		Plugin.CustomReforges.add(new Reforge("Rainbow's Donkey",
				0,
				100,
				0,
				-20,
				-20,
				0,
				0,
				0,
				0,
				"Legendary",
				new ItemStack(Material.ARROW).getItemMeta(),
				"Assed",
				0,
				"Any",
				0));
		Plugin.CustomReforges.add(new Reforge("PJ's Finch",
				-10,
				-10,
				0,
				0,
				+30,
				+5,
				+5,
				0,
				0,
				"Legendary",
				new ItemStack(Material.ARROW).getItemMeta(),
				"Savannan",
				0,
				"Any",
				0));


//		ItemStats.RegisteredReforges[0][0] = "Strength Artifact";
//		ItemStats.RegisteredReforges[0][1] = "Strong";
//		ItemStats.RegisteredReforges[1][0] = "Aegis of Zeus";
//		ItemStats.RegisteredReforges[1][1] = "Reinforced";
//		ItemStats.RegisteredReforges[2][0] = "The Wizards Last Wish";
//		ItemStats.RegisteredReforges[2][1] = "Smart";
	}

	@Override
	public void onDisable() {
		// Plugin shutdown logic
	}

	public static Plugin getInstance() {
		return (Plugin) Bukkit.getServer().getPluginManager().getPlugin("MMORPGCustom");
	}
}
