name: MMORPGCustom
version: '${project.version}'
main: me.dnfneca.plugin.Plugin
api-version: 1.18
authors: [ DNFneca ]
commands:
  summon:
    description: summon a custom mob from the plugin
    usage: /summon