name: MMORPGCustom
version: '${project.version}'
main: me.dnfneca.plugin.Plugin
api-version: 1.18
authors: [ DNFneca ]
commands:
  summonmob:
    description: summon a custom mob from the plugin
    usage: /summon
  giveitem:
    description: gives an item you name
    usage: /giveitem
  classreset:
    description: resets the class for the mentioned player, or for the command sender in noone is mentioned
    usage: /classreset
  GUI:
    description: A test GUI
    usage: /gui
  GOD:
    description: a command to make you invincible
    usage: /god
  getregistereditems:
    description: get all the registered items
    usage: /getregistereditems
  getregisteredreforges:
    description: a command for getting al the registered reforges' names and buffs
    usage: /getregistedreforges