name: MMORPGCustom
version: '${project.version}'
main: me.dnfneca.plugin.Plugin
api-version: 1.18
authors: [ DNFneca ]
commands:
  summonmob:
    description: summon a custom mob from the plugin
    usage: /summon
  item:
    description: gives an item you name
    usage: /item
  classreset:
    description: resets the class for the mentioned player, or for the command sender in noone is mentioned
    usage: /classreset
  NPC:
    description: resets the class for the mentioned player, or for the command sender in noone is mentioned
    usage: /NPC
  deleteEveryNPC:
    description: cum
    usage: /deleteEveryNPC
  GUI:
    description: A test GUI
    usage: /gui